/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import gnu.io.CommPort;
import gnu.io.CommPortIdentifier;
import gnu.io.PortInUseException;
import gnu.io.SerialPort;
import gnu.io.UnsupportedCommOperationException;
import java.io.IOException;
import java.io.PrintStream;
import java.util.Enumeration;
import java.util.Scanner;

/**
 *
 * @author Diego Ramos
 */
public class Pesaje extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form Pesaje
     */
 public static Double peso;
 int contadorHilos = 0;
 CommPortIdentifier cpi = null;
    SerialPort puertoSerial = null;
    Scanner entrada = null;
    PrintStream salida = null;
    Enumeration comports = CommPortIdentifier.getPortIdentifiers();
 
    public Pesaje() {
        initComponents();
        Thread hilo = new Thread(this);
        hilo.start();
        
    }

    
    
     private void getPuerto(){
    
    while(comports.hasMoreElements()){
    cpi = (CommPortIdentifier) comports.nextElement();
    if(cpi.getName().equals("COM2")){
        break;
    }
    }
    
        try {
            CommPort puerto = cpi.open("Puerto Serial",5000);
            puertoSerial = (SerialPort) puerto;
            puertoSerial.setSerialPortParams(19200, SerialPort.DATABITS_8, SerialPort.STOPBITS_1, SerialPort.PARITY_NONE);
            entrada = new Scanner(puertoSerial.getInputStream());
            salida = new PrintStream(puertoSerial.getOutputStream());
        } catch (PortInUseException ex) {
            //Logger.getLogger(pesaje.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            //Logger.getLogger(pesaje.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedCommOperationException ex) {
            //Logger.getLogger(pesaje.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        while(!entrada.hasNextDouble()){
            entrada.close();
            entrada = null;
        try {
            entrada = new Scanner(puertoSerial.getInputStream());
            salida = new PrintStream(puertoSerial.getOutputStream());
        } catch (IOException ex) {
            
            //Logger.getLogger(pesaje.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        }
        peso = entrada.nextDouble();
        System.out.println("Peso: "+peso);
        peso=0.0;
        //salida.println("Dato capturado");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pesaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pesaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pesaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pesaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pesaje().setVisible(true);
            }
        });
    }

    @Override
    public void run() {
        while(true){
            contadorHilos++;
            System.out.println("Hilos: "+contadorHilos);
            getPuerto();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
