/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import gnu.io.CommPort;
import gnu.io.CommPortIdentifier;
import gnu.io.PortInUseException;
import gnu.io.SerialPort;
import gnu.io.UnsupportedCommOperationException;
import java.io.IOException;
import java.io.PrintStream;
import java.util.Enumeration;
import java.util.Scanner;

/**
 *
 * @author Diego Ramos
 */
public class Pesaje extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form Pesaje
     */
 public static Double peso = 0.0;
 public static Double pesoOld=0.0;
 public static Integer contador = 0;
 public static int contadorHilos = 0;
 CommPortIdentifier cpi = null;
    SerialPort puertoSerial = null;
    Scanner entrada = null;
    PrintStream salida = null;
    Enumeration comports = CommPortIdentifier.getPortIdentifiers();
    Boolean bandera=false;
 
    public Pesaje() {
        initComponents();
         this.setLocationRelativeTo(null);
        //this.setExtendedState(MAXIMIZED_BOTH);
        Thread hilo = new Thread(this);
        hilo.start();
        MostrarLabels(false);
        
    }

    
    
     private void getPuerto(){
    
    while(comports.hasMoreElements()){
    cpi = (CommPortIdentifier) comports.nextElement();
    if(cpi.getName().equals("COM2")){
        break;
    }
    }
    
        try {
            CommPort puerto = cpi.open("Puerto Serial",5000);
            puertoSerial = (SerialPort) puerto;
            puertoSerial.setSerialPortParams(19200, SerialPort.DATABITS_8, SerialPort.STOPBITS_1, SerialPort.PARITY_NONE);
            entrada = new Scanner(puertoSerial.getInputStream());
            salida = new PrintStream(puertoSerial.getOutputStream());
        } catch (PortInUseException ex) {
            //Logger.getLogger(pesaje.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            //Logger.getLogger(pesaje.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedCommOperationException ex) {
            //Logger.getLogger(pesaje.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        while(!entrada.hasNextDouble()){
            entrada.close();
            entrada = null;
        try {
            entrada = new Scanner(puertoSerial.getInputStream());
            salida = new PrintStream(puertoSerial.getOutputStream());
        } catch (IOException ex) {
            
            //Logger.getLogger(pesaje.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        }
        peso = entrada.nextDouble();
        txtaPesos.append(peso.toString()+System.getProperty("line.separator"));
        System.out.println("Peso: "+peso);
       
        if(pesoOld.equals(peso)){
             contador++;
             System.out.println("contador mas"+contador);
         }else{contador=0;
        System.out.println("contador menos"+contador);}
         
         if(contador==10){
             lblPesoTotal.setText(peso.toString());
             MostrarLabels(false);
             lblDescripcion2.setVisible(true);
        lblPesoTotal.setVisible(true);
         }
         pesoOld=peso;
        
        
//        peso=0.0;
        //salida.println("Dato capturado");
        
    }
     
     public static void MostrarLabels(Boolean visible){
        lblCarga.setVisible(visible);
        lblCalculando.setVisible(visible);
        lblDescripcion1.setVisible(visible);
        lblDescripcion2.setVisible(visible);
        lblPesoTotal.setVisible(visible);
        jScrollPane1.setVisible(visible);
        txtaPesos.setVisible(visible);
     }
     
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCarga = new javax.swing.JLabel();
        lblCalculando = new javax.swing.JLabel();
        lblDescripcion2 = new javax.swing.JLabel();
        btnEmpezar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaPesos = new javax.swing.JTextArea();
        lblDescripcion1 = new javax.swing.JLabel();
        lblPesoTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 102));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Pesaje de Sacos de Cafe Olopa");

        lblCarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cargando.gif"))); // NOI18N

        lblCalculando.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblCalculando.setText("Calculando");

        lblDescripcion2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblDescripcion2.setText("El peso final es de:");

        btnEmpezar.setBackground(new java.awt.Color(255, 153, 102));
        btnEmpezar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnEmpezar.setText("Empezar");
        btnEmpezar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 204)));
        btnEmpezar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpezarActionPerformed(evt);
            }
        });

        txtaPesos.setBackground(new java.awt.Color(255, 153, 102));
        txtaPesos.setColumns(20);
        txtaPesos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtaPesos.setRows(5);
        jScrollPane1.setViewportView(txtaPesos);

        lblDescripcion1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblDescripcion1.setText("El Peso es de: ");

        lblPesoTotal.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        lblPesoTotal.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDescripcion2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPesoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(358, 358, 358)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCarga)
                    .addComponent(btnEmpezar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCalculando, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(220, 220, 220)
                    .addComponent(lblDescripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(453, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEmpezar)
                        .addGap(55, 55, 55)
                        .addComponent(lblCarga)
                        .addGap(18, 18, 18)
                        .addComponent(lblCalculando, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(229, 229, 229)
                                .addComponent(lblPesoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblDescripcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(450, Short.MAX_VALUE)
                    .addComponent(lblDescripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(257, 257, 257)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpezarActionPerformed
     bandera=true;
     MostrarLabels(true);
     
    }//GEN-LAST:event_btnEmpezarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pesaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pesaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pesaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pesaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pesaje().setVisible(true);
            }
        });
    }

    @Override
    public void run() {
        while(true){
            contadorHilos++;
            System.out.println("Hilos: "+contadorHilos);
            getPuerto();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnEmpezar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblCalculando;
    public static javax.swing.JLabel lblCarga;
    public static javax.swing.JLabel lblDescripcion1;
    public static javax.swing.JLabel lblDescripcion2;
    public static javax.swing.JLabel lblPesoTotal;
    public static javax.swing.JTextArea txtaPesos;
    // End of variables declaration//GEN-END:variables
}
